### ISSUE TITLE
username error

### ISSUE THREAD

**Issue by suvithk1** [varshanbp/Digital-Attendance#1]
while inputting data while registering for new user  the username size is very less only 6 char i think it should be increased to minimum 15-20

**Comment by varshanbp** [comment]
To prevent unwanted confusions and long username, my suggestion is that 6 is better. Comments expected.

**Comment by varshanbp** [comment]
Please provide your suggestions

**Comment by varshanbp** [comment]
No reply for past few days. Hence as of now no change.
